from django.urls import path
from django.contrib import admin
from . import views
from .forms import UserLoginForm
from django.contrib.auth.views import LoginView
from django.conf import  settings
from django.conf.urls.static import static

app_name = 'tutor'

urlpatterns = [
    path("", views.home, name="home"),
    path(
        'login/',
        LoginView.as_view(template_name="tutor/login.html", authentication_form=UserLoginForm),
        name="login"),
    path("tutor/register/", views.tutor_redirect, name="register"),
    path("tutor/login/",views.login_redirect, name="login"),
    path("register/", views.register, name="register"),
    path("not-qualified/", views.not_qualified, name="not-qualified"),
    path("k-12-registration/", views.k_12_registration, name="k-12-registration"),
    path("onboard/", views.onboard, name="onboard"),
    path("onboard/monthly/", views.tutor_onboard_monthly, name="tutor-onboard-monthly"),
    path("onboard/weekly/", views.tutor_onboard_weekly, name="tutor-onboard-weekly"),
    path("monthly-weekly/", views.monthly_weekly_info, name="monthly-weekly-info"),
    path("register/site/", views.site_registration, name="site_registration"),
    
    path("admin_forecast/", views.admin_hours_forecast, name="admin_hours"),

    path("request/", views.request, name="request"),
    path("request/new/", views.student_request_new, name="request-new"),
    path("request/manage/", views.student_request_manage, name="request-manage"),
    path("requests/rerequest/", views.student_request_rerequest, name="request-rerequest"),
    path("requests/unfulfilled/", views.unfulfilled_requests, name="unfulfilled-requests"),
    path("requests/match/", views.tutor_match, name="tutor-match"),
    path("requests/match/<int:request_id>/<int:timeslot_id>", views.tutor_match_confirm, name="tutor-match-confirm"),
    path("requests/match/thankyou/", views.tutor_match_done, name="tutor-match-done"),

    path("meeting/", views.meeting, name="meeting"),
    path("college-registration/", views.college_registration, name="college-registration"),
    path("adult-education-registration/", views.adult_education_registration, name="adult-education-registration"),
    path("tutor-registration/", views.tutor_registration, name="tutor-registration"),
    path("tutor_portal/", views.manage, name="tutor_portal"),
    path("tutee_portal/", views.tutee_portal, name="tutee_portal"),
    path("clock/", views.clock, name="clock"),
    path("clock/assessment/<int:meeting_id>/", views.clock_assessment, name="clock_assessment"),
    path("training/", views.training, name="training"),
    path("training/orientation/", views.orientation, name="orientation"),
    path("clock/rate/<int:unrated_meeting_id>/", views.clock_rate, name="clock_rate"),

    path("manage/", views.manage, name="manage"),
    path("directory/", views.directory, name="directory"),
    path("add_student/", views.add_student, name = "add_student"),
    path("support/", views.support, name="support"),
    path("harass_issue/", views.harass_issue, name="harass_issue"),
    path("profile/", views.profile, name="profile"),
    path("profile/hours/", views.profile_tutor_hours, name="profile-hours"),
    path("profile/<int:user_id>", views.profile_public, name="profile_public"),
    path("background/", views.background, name="background"),
    path("site_portal/", views.site_log, name="site_portal"),
    path("site_log/", views.site_log, name="site_log"),
    path("site_log/<int:location_id>/", views.site_log, name="site_log"),
    path("site/download/", views.site_download, name="site_download"),
    path("site/download/<int:site_location_id>/", views.site_download, name="site_location_download"),
    path("database/download/", views.database_download, name="database_download"),
    path("site/requests/", views.site_requests, name="site-requests"),
    path("site/requests/<int:location_id>/", views.site_requests, name="site-requests"),
    path("site/requests/cancel/<int:request_id>", views.site_cancel_request, name="site-cancel-request"),
    path("site/requests/new/", views.site_new_request, name="site-new-request"),
    path("site/requests/<int:location_id>/new/", views.site_new_request, name="site-new-request"),
    path("site/requests/new/<int:student_id>/", views.site_new_request_student, name="site-new-request-student"),
    path("site/confirmations/", views.site_confirmations, name="site-confirmations"),
    path("site/confirmations/<int:location_id>/", views.site_confirmations, name="site-confirmations"),
    path("session/<int:session_id>/", views.session_detail, name="session_detail"),
    path("exitticket/", views.exit_ticket, name="exit-ticket"),
    path("leaveticket/", views.leave_ticket, name="leave-ticket"),
    path("orientation_1c/", views.orientation_1c, name="orientation-1c"),
    path("orientation_1h/", views.orientation_1h, name="orientation-1h"),
    path("orientation_1r/", views.orientation_1r, name="orientation-1r"),
    path("orientation_1w/", views.orientation_1w, name="orientation-1w"),
    path("orientation_2/", views.orientation_2, name="orientation-2"),
    path("orientation_3/", views.orientation_3, name="orientation-3"),
    path("orientation_4/", views.orientation_4, name="orientation-4"),
    path("orientation_5/", views.orientation_5, name="orientation-5"),
    path("orientation_6/", views.orientation_6, name="orientation-6"),
    path("orientation_7/", views.orientation_7, name="orientation-7"),
    path("orientation_8/", views.orientation_8, name="orientation-8"),
    path("orientation_9/", views.orientation_9, name="orientation-9"),
    path("orientation_10/", views.orientation_10, name="orientation-10"),
    path("orientation_11/", views.orientation_11, name="orientation-11"),
    path("orientation_content/", views.orientation_content, name="orientation-content"),
    path("live_training/", views.orientation_live_session, name="live-training"),
    path("past_meetings/", views.past_meetings, name="past-meetings"),
]
