# Generated by Django 3.2.5 on 2022-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_tutorrequest_inactive_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmembership',
            name='cancel_reason',
            field=models.TextField(choices=[('', '----'), ('User', 'User'), ('Unconfirmed', 'Unconfirmed')], default='', null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='cancel_reason',
            field=models.TextField(choices=[('', '----'), ('User', 'User'), ('Unconfirmed', 'Unconfirmed')], default='', null=True),
        ),
    ]
