# Generated by Django 3.2.5 on 2022-02-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_auto_20220221_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmembership',
            name='cancel_reason',
            field=models.TextField(blank=True, choices=[('', '----'), ('User', 'User'), ('Unconfirmed', 'Unconfirmed')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='cancel_reason',
            field=models.TextField(blank=True, choices=[('', '----'), ('User', 'User'), ('Unconfirmed', 'Unconfirmed')], default='', null=True),
        ),
    ]
