# Generated by Django 3.2.5 on 2022-02-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20220221_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmembership',
            name='cancel_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
