# Generated by Django 3.2.5 on 2022-02-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_meetingmembership_cancel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmembership',
            name='cancel_reason',
            field=models.TextField(blank=True, choices=[('', '----'), ('User', 'User'), ('Cancelled Request', 'Cancelled Request'), ('Unconfirmed', 'Unconfirmed')], default='', null=True),
        ),
    ]
