# Generated by Django 3.2.5 on 2022-02-24 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_alter_meetingmembership_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 24, 19, 27, 12, 98928, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
