# Generated by Django 3.2.5 on 2022-03-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_meeting_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approve_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
