# Generated by Django 3.2.5 on 2022-03-06 02:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0010_profile_approve_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block',
            field=models.ManyToManyField(blank=True, related_name='blocking', to=settings.AUTH_USER_MODEL),
        ),
    ]
