# Generated by Django 3.2.5 on 2022-03-11 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0011_profile_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='attendance',
            field=models.ManyToManyField(blank=True, related_name='attended_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='follow_up_meeting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor.meeting'),
        ),
    ]
