# Generated by Django 3.2.5 on 2022-03-22 03:16

from django.db import migrations
from tutor.models import get_grade_levels

def add_grade_levels(apps, schema_editor):
    GradeLevel = apps.get_model("tutor", "GradeLevel")
    for grade, _ in get_grade_levels():
        GradeLevel.objects.create(display=grade)


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_auto_20220321_2316'),
    ]

    operations = [
        migrations.RunPython(add_grade_levels),
    ]
