# Generated by Django 3.2.5 on 2022-03-27 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0015_auto_20220321_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitticketdifficult',
            name='comfortable_reason',
            field=models.TextField(blank=True, default=None, help_text='This information will be used to help us make changes to our program to better support you and other students in the future', null=True, verbose_name='If you rated the tutor 2 or below for the question above, please provide any additional comments here'),
        ),
        migrations.AlterField(
            model_name='exitticketdifficult',
            name='helpful_reason',
            field=models.TextField(blank=True, default=None, help_text='This information will be used to help us make changes to our program to better support you and other students in the future', null=True, verbose_name='If you rated the tutor 2 or below for the question above, please provide any additional comments here'),
        ),
        migrations.AlterField(
            model_name='exitticketdifficult',
            name='satisfaction_reason',
            field=models.TextField(blank=True, default=None, help_text='This information will be used to help us make changes to our program to better support you and other students in the future', null=True, verbose_name='If you rated the tutor 2 or below for the question above, please provide any additional comments here'),
        ),
        migrations.AlterField(
            model_name='exitticketdifficult',
            name='still_help',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='Do you still need help with any concepts/problems?'),
        ),
        migrations.AlterField(
            model_name='exitticketdifficult',
            name='thank_letter_yesno',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='Have you sent a thank you email to the tutor?'),
        ),
        migrations.AlterField(
            model_name='exitticketdifficult',
            name='tutor_helpful',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='How helpful was the tutor in guiding you to understand concepts/problems?'),
        ),
        migrations.AlterField(
            model_name='exitticketeasy',
            name='like_tutor',
            field=models.BooleanField(choices=[(True, 'Yes 😃'), (False, 'No 🙁')], default=None, verbose_name='I like the tutor.'),
        ),
        migrations.AlterField(
            model_name='exitticketeasy',
            name='safe_mistakes',
            field=models.BooleanField(choices=[(True, 'Yes 😃'), (False, 'No 🙁')], default=None, verbose_name='I feel safe to make mistakes in the tutorial.'),
        ),
        migrations.AlterField(
            model_name='exitticketeasy',
            name='tutor_helps',
            field=models.BooleanField(choices=[(True, 'Yes 😃'), (False, 'No 🙁')], default=None, verbose_name='When I don’t understand something, my tutor helps me.'),
        ),
        migrations.AlterField(
            model_name='exitticketeasy',
            name='understand_better',
            field=models.BooleanField(choices=[(True, 'Yes 😃'), (False, 'No 🙁')], default=None, verbose_name='I understand better when I work with the tutor.'),
        ),
        migrations.AlterField(
            model_name='exitticketmedium',
            name='be_open',
            field=models.CharField(choices=[('NEVER', 'Never'), ('SOMETIMES', 'Sometimes'), ('ALWAYS', 'Always')], default=None, max_length=10, verbose_name='Do you feel you can be open with the material you are having difficulty with in the tutorial session?'),
        ),
        migrations.AlterField(
            model_name='exitticketmedium',
            name='better_understand',
            field=models.CharField(choices=[('NEVER', 'Never'), ('SOMETIMES', 'Sometimes'), ('ALWAYS', 'Always')], default=None, max_length=10, verbose_name='Do you feel you better understand the material as a result of working with the tutor?'),
        ),
        migrations.AlterField(
            model_name='exitticketmedium',
            name='like_tutor',
            field=models.CharField(choices=[('NEVER', 'Never'), ('SOMETIMES', 'Sometimes'), ('ALWAYS', 'Always')], default=None, max_length=10, verbose_name='Did you like working with the tutor?'),
        ),
        migrations.AlterField(
            model_name='exitticketmedium',
            name='tutor_help',
            field=models.CharField(choices=[('NEVER', 'Never'), ('SOMETIMES', 'Sometimes'), ('ALWAYS', 'Always')], default=None, max_length=10, verbose_name='When you are having difficulty with an assignment, does the tutor help you?'),
        ),
    ]
