# Generated by Django 3.2.5 on 2022-04-21 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0016_auto_20220327_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmembership',
            name='confirmation_timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='meetingmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
