# Generated by Django 3.2.5 on 2022-05-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0017_auto_20220420_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmembership',
            name='confirmation_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
