# Generated by Django 3.2.5 on 2022-06-22 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0020_auto_20220519_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orientationtraining',
            name='tutor_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientation_training_form', to='tutor.profile', verbose_name='Who was your tutor trainer?'),
        ),
        migrations.AlterField(
            model_name='roleplaytraining',
            name='tutor_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roleplay_training_form', to='tutor.profile', verbose_name='Who was your tutor trainer?'),
        ),
        migrations.AlterField(
            model_name='tutortraining',
            name='tutor_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_training_form', to='tutor.profile', verbose_name='Who was your tutor trainer?'),
        ),
    ]
