# Generated by Django 3.2.5 on 2022-08-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0022_merge_0021_auto_20220622_0234_0021_auto_20220719_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='binding',
            field=models.BooleanField(default=False),
        ),
    ]
