# Generated by Django 3.2.5 on 2022-08-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0023_site_binding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='binding',
        ),
        migrations.AddField(
            model_name='sitelocation',
            name='binding',
            field=models.BooleanField(default=False),
        ),
    ]
