# Generated by Django 3.2.5 on 2022-08-18 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0024_auto_20220810_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.DateTimeField(blank=True, default=None, null=True)),
                ('leave_reason', models.TextField(max_length=200)),
                ('leave_reason_others', models.TextField(max_length=200)),
                ('return_date', models.DateField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
