# Generated by Django 3.2.5 on 2022-09-12 00:36

from django.db import migrations
from tutor.models import(
    LiveSession,
    Orientation1,
    Orientation2,
    Orientation3,
    Orientation4,
    Orientation5,
    Orientation6,
    Orientation7,
    Orientation8,
    Orientation9,
    Orientation10,
    Orientation11,
    User
) 

def populate_training(apps, schema_editor):
    tutor = User.objects.filter(profile__account_type__display = "Tutor")

    for users in tutor:
        try:
            record = users.orientationtraining
            record = users.roleplaytraining
            record = users.tutortraining
            Orientation1.objects.create(user = users)
            Orientation2.objects.create(user = users)
            Orientation3.objects.create(user = users)
            Orientation4.objects.create(user = users)
            LiveSession.objects.create(user = users)
        except:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0026_livesession_orientation1_orientation10_orientation11_orientation2_orientation3_orientation4_orientat'),
    ]

    operations = [
        migrations.RunPython(populate_training),
    ]