# Generated by Django 3.2.5 on 2022-11-03 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0028_auto_20221004_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tutor.profile',),
        ),
    ]
