# Generated by Django 3.2.5 on 2022-11-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0030_auto_20221103_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmembership',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
