# Generated by Django 3.2.5 on 2022-12-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0031_meetingmembership_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmembership',
            name='rated',
            field=models.BooleanField(default=True),
        ),
    ]
