# Generated by Django 3.2.5 on 2022-12-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0032_meetingmembership_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmembership',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
