# Generated by Django 3.2.5 on 2023-02-04 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0033_alter_meetingmembership_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorofferedmonthlyhours',
            name='m_3_23',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='MAR 2023'),
        ),
        migrations.AddField(
            model_name='tutorofferedmonthlyhours',
            name='m_4_23',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='APR 2023'),
        ),
        migrations.AddField(
            model_name='tutorofferedmonthlyhours',
            name='m_5_23',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='MAY 2023'),
        ),
        migrations.AddField(
            model_name='tutorofferedmonthlyhours',
            name='m_6_23',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='JUN 2023'),
        ),
        migrations.AddField(
            model_name='tutorofferedmonthlyhours',
            name='m_7_23',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='JUL 2023'),
        ),
        migrations.AddField(
            model_name='tutorofferedmonthlyhours',
            name='m_8_23',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='AUG 2023'),
        ),
    ]
