# Generated by Django 3.2.5 on 2023-04-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0035_connectedstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuteeassessment',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
