# Generated by Django 3.2.5 on 2021-11-28 19:25

from django.db import migrations
import re
import csv
import string
import calendar
import random
from datetime import datetime




def setup_test(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("tutor", "Profile")
    TimeSlot = apps.get_model("tutor", "TimeSlot")
    Subject = apps.get_model("tutor", "Subject")
    Sector = apps.get_model("tutor", "Sector")
    Site = apps.get_model("tutor", "Site")
    Pronouns = apps.get_model("tutor", "Pronouns")
    AccountType = apps.get_model("tutor", "AccountType")
    BackgroundCheckRequest = apps.get_model("tutor", "BackgroundCheckRequest")

    def add_backgroundcheckrequest(user, record):
        status = "Queued"
        if record['Completed BC?'] == 'x':
            status = "Approved"
        BackgroundCheckRequest.objects.create(
            user=user,
            status=status,
        )

    def add_phone_number(profile, record):
        profile.phone_number = re.sub(r"[^0-9]", "", record['Phone Number'])
        profile.save()

    with open("users.csv") as f:
        reader = csv.DictReader(f)
        records = list(reader)

    for record in records:
        # testing record
        user_id = record['Tutor ID']
        user = None
        if user_id.startswith("TT"):
            continue
        try:
            user = User.objects.get(username=user_id)
        except User.DoesNotExist:
            continue
        profile = user.profile
        add_backgroundcheckrequest(user, record)
        add_phone_number(profile, record)


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_manual_migration'),
    ]

    operations = [
        migrations.RunPython(setup_test),
    ]
