# Generated by Django 3.2.5 on 2022-08-07 20:31

from django.db import migrations
import time
from datetime import datetime
from calendar import day_name

from django.db import migrations, transaction
from tutor.models import get_time_slots, get_subjects, get_sites, get_sectors, get_genders, get_ethnicities, get_pronouns, get_account_types, get_site_locations, get_site_tier, get_tiers


def add_questions(apps, schema_editor):
    Tier = apps.get_model("tutor", "Tier")
    Site = apps.get_model("tutor", "Site")
    SiteLocation = apps.get_model("tutor", "SiteLocation")
    for site, _ in get_sites():
        if Site.objects.filter(display=site):
            continue
        site_tier = get_site_tier(site)
        site_obj = Site.objects.create(display=site, tier=Tier.objects.get(display=site_tier))
        for site_location, _ in get_site_locations(site):
            site_location_obj = SiteLocation.objects.create(display=site_location, site=site_obj)

class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0023_alter_timeslot_display'),
    ]

    operations = [
        migrations.RunPython(add_questions),
    ]
